# Site settings
title:          Sangwan's blog
description:    "Staff Software Engineer"
baseurl:        "/tale"
url:            "https://bitboom.github.io"

# Google Analytics
google_analytics: UA-136014324-1

# Author
author:
  name:         Sangwan Kwon
  url:          https://sangwan.dev/
  email:        bitboom9@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
#  - jemoji

remote_theme: chesterhow/tale

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec, _drafts ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
